using Npgsql;
using System.Data;

namespace WelcomePage.Data;

public class DbContext
{
    private const string ConnectionString = "Host=127.0.0.1;Port=5433;Username=admin;Password=admin1234;Database=AppPgDb";

    public IDbConnection CreateConnection()
    {
        return new NpgsqlConnection(ConnectionString);
    }

    public void EnsureSchema()
    {
        using var connection = CreateConnection();
        connection.Open();

        using var command = connection.CreateCommand();
        command.CommandText = @"
            CREATE TABLE IF NOT EXISTS Users (
                UserId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                Username TEXT NOT NULL UNIQUE,
                PasswordHash TEXT NOT NULL,
                FirstName TEXT NOT NULL,
                LastName TEXT NOT NULL,
                DateOfBirth TEXT NOT NULL,
                CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS Friends (
                UserId INTEGER NOT NULL,
                FriendUserId INTEGER NOT NULL,
                CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT PK_Friends PRIMARY KEY (UserId, FriendUserId),
                CONSTRAINT FK_Friends_User FOREIGN KEY (UserId) REFERENCES Users (UserId) ON DELETE CASCADE,
                CONSTRAINT FK_Friends_Friend FOREIGN KEY (FriendUserId) REFERENCES Users (UserId) ON DELETE CASCADE
            );";
        command.ExecuteNonQuery();
    }
}